version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      FLASK_APP: "app.py"
    volumes:
      - type: tmpfs
        target: /project/migrations
    networks:
      - app-net
    depends_on:
      db:
        condition: service_healthy
    expose:
      - 5000

  nginx:
    build:
      context: ./nginx
      args:
        - DATABASE_CODE=DB1-LITE  # Меняем на DB3-LITE для определения городов
        - TOKEN=9trA2fVahwyNaj7iRSaRHqfwzQgFqJMQWI7KKBOjV6XRXkU6x57b1fUbGyDtan88
    ports:
      - "80:80"
    networks:
      - app-net
    depends_on:
      - web
      
volumes:
  postgres_data:

networks:
  app-net: